channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0.3
  - r-rcpp
  - r-tidyverse
  - r-factoextra
  - r-pheatmap
  - r-gert
  - r-irkernel
  - r-later
  - r-lubridate
  - r-biocmanager
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-limma
  - bioconductor-edger
  - bioconductor-annotationdbi
  - bioconductor-org.hs.eg.db
  - bioconductor-graph
  - bioconductor-go.db
  - bioconductor-topgo

